### ISSUE TITLE
Add "Show in Inventory" and "Show in Escape Menu" option.

### ISSUE THREAD

**Issue by leafable** [isXander/EvergreenHUD#140]
Just basically the title. Adds an option to "Visibility" to show a module in your inventory or escape menu.

**Comment by Wyvest** [comment]
Already exists, its called show in GUIs

**Comment by leafable** [comment]
True, but they aren't separate. Just a suggestion, you do what you think is best.

**Comment by isXander** [comment]
i see no case where this would be useful
