### ISSUE TITLE
Crash on 1.18.2

### ISSUE THREAD

**Issue by OhaDerErste** [isXander/EvergreenHUD#214]
**Describe the bug**

**To Reproduce**
1. Start the game

**Expected behavior**
Game should start

**Crash report**
https://paste.horlboge.de/oxixugulex.sql

**Screenshots**

**EvergreenHUD Info (please complete the following information):**
- Mod Version: 2.0.0-alpha.5-1.18.2-c8a97c9
- Minecraft Version Fabric 1.18.2

**Additional context**
My other mods  
![image](https://user-images.githubusercontent.com/77100649/157117181-ad7afa1f-ae57-49e0-9bad-84a751744399.png)

**Comment by isXander** [comment]
Looks like this is an issue with the Iris mod. If not, reopen the issue.

**Comment by isXander** [comment]
reopned as it seems like this is in fact a me issue
