### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ItzMeBlaze** [isXander/EvergreenHUD#22]
can you help me build a custom client called VulnerabilityClient? please tell me...

**Comment by isXander** [comment]
not related to evergreenhud

**Comment by ItzMeBlaze** [comment]
Bye

**Comment by MatthewTGM** [comment]
Are you dumb..?

**Comment by koxx12-dev** [comment]
@MatthewTGM this is minecraft mod so what did you expect, most of the pp that use mods have less then 3 braincells and dont know how to use cmd

**Comment by MatthewTGM** [comment]
> @MatthewTGM this is minecraft mod so what did you expect, most of the ppl that use mods have less then 3 braincells and dont know how to use cmd

Yeah but... "can you help me with my client?" bruh

**Comment by koxx12-dev** [comment]
_prob he even doesnt know basic c# to make the launcher or java to code that thing_

**Comment by ItzMeBlaze** [comment]
lmao i was testing me and my friend have made a bot and a client called
phobos 1.9.0 search about phobos.

**Comment by wag06** [comment]
no one cares

**Comment by ItzMeBlaze** [comment]
lmfao search phobos 1.9.0 you will be a fan of me.

**Comment by koxx12-dev** [comment]
_phobos is a hacked client with a backdoor_

**Comment by koxx12-dev** [comment]
_there is a clean version that is made by not you_

**Comment by koxx12-dev** [comment]
_so stop being cringe_
