### ISSUE TITLE
Bug Report - Coords hud not updating like legacy

### ISSUE THREAD

**Issue by Zetvue** [isXander/EvergreenHUD#223]
**Describe the bug**
Coords hud does not update fast.

**To Reproduce**
1. Use coords hud

**Expected behavior**
Update like it did on legacy

**EvergreenHUD Info (please complete the following information):**
- Mod Version: [e.g. 2.0.0-alpha 6]
- Minecraft Version [e.g. 1.18.2]

**Comment by Deftu** [comment]
That is a feature. Open your coords instance's settings menu and look for a setting relating to update times. (based on ticks, I believe?)

**Comment by isXander** [comment]
Set the cache time to 0 if you want it to update instantly.
