### ISSUE TITLE
ArmourHUD background is in the wrong place

### ISSUE THREAD

**Issue by he3als** [isXander/EvergreenHUD#24]
**Describe the bug**
The background of the armour HUD is not in the right place.

**To Reproduce**
1. Use right alignment
2. List type: up
3. You will see

**Expected behavior**
I expected the background to be where the actual armour HUD is.

**Screenshots**
![image](https://user-images.githubusercontent.com/65787561/128340295-5704e95e-df71-4e85-9dc8-35ac12a091fa.png)

**EvergreenHUD Info (please complete the following information):**
 - Mod Version: 2.0.0.94-pre.12 
 - Minecraft Version: 1.8.9

**Comment by koxx12-dev** [comment]
known issue

**Comment by koxx12-dev** [comment]
will be fixed in the rewrite

**Comment by isXander** [comment]
fixed in fbcccba
