### ISSUE TITLE
General GUI problems

### ISSUE THREAD

**Issue by mirronake** [isXander/EvergreenHUD#247]
**Describe the bug**
The buttons don't work, the delete and settings buttons for widgets move out. There are a lot of mistakes in fashion.

**Screenshots**
![Base Profile Screenshot 2022 04 27 - 10 00 13 38](https://user-images.githubusercontent.com/96698262/165460217-95ebcabf-4c0e-4dcd-a259-664dd5a8998b.png)

Mod Version: [2.0.0-alpha.6]
- Minecraft Version [1.18.2]

**Additional context**

**Comment by isXander** [comment]
im aware. alpha remember. gui broken
