### ISSUE TITLE
Duplicate MixinExtras on quilt

### ISSUE THREAD

**Issue by DioEgizio** [isXander/EvergreenHUD#248]
**Describe the bug**
the mod breaks on Quilt

**To Reproduce**
use this mods on quilt and see

**Crash report**
https://0x0.st/oTdP.txt

**Screenshots**
<img width="912" alt="image" src="https://user-images.githubusercontent.com/83089242/165586051-35c426e2-243d-437d-b632-7c8acb9e9971.png">

**EvergreenHUD Info (please complete the following information):**
- Mod Version: [2.0.0-alpha.6]
- Minecraft Version [1.18.2]

**Comment by isXander** [comment]
same as isXander/Zoomify#20
