### ISSUE TITLE
CPS mod is incorrect

### ISSUE THREAD

**Issue by he3als** [isXander/EvergreenHUD#25]
**Describe the bug**
I am clicking 20 CPS and it is saying I am only clicking 5. I have tried with a 50 CPS autoclicker as well, it only said 10 on the CPS counter.

**To Reproduce**
1. Add the CPS mod to your HUD
2. Click fast
3. Look at the CPS mod

**Expected behavior**
I expected it to be correct.

**Screenshots**
https://i.imgur.com/aYwp8lB.gif

**EvergreenHUD Info (please complete the following information):**
 - Mod Version: 2.0.0.94-pre.12 
 - Minecraft Version: 1.8.9

**Additional context**
I tried this in a server as well, no difference.

**Comment by koxx12-dev** [comment]
_should_ work correctly with raw input mode

**Comment by he3als** [comment]
yeah sorry i just realised that
