### ISSUE TITLE
Cps Counter

### ISSUE THREAD

**Issue by syedabdulahad465** [isXander/EvergreenHUD#26]
So cps counter is bugged i check it with sk1er keystrokes and i was clicking 12 cps but on your mod it showed me  to 7 cps??
then i tried butterflying clicking with double clicking 18 cps it shows 10 cps, just to be sure i went to a cps site and tested out that it was my mouse or not then i got 18 cps with butterflying clicking

**Comment by koxx12-dev** [comment]
change to raw input mode

**Comment by koxx12-dev** [comment]
in settings of cps counter
