### ISSUE TITLE
Couldn't build mod

### ISSUE THREAD

**Issue by LuciusofLegend** [isXander/EvergreenHUD#269]
**Describe the bug**
I went through the usual steps I use to build mods from github, and it said build failed.

**To Reproduce**
1. Go to 'Code'
2. Click on 'Download Zip'
3. Extract the .zip file
4. Enter the folder generated
5. Right click inside the folder
6. Open your console
7. For windows, type "gradlew build", if you're on linux type "chmod +x gradlew" and then "gradlew build"
8. Build fails.

**Expected behavior**
I expected the build to work.

**Crash report**

Script compilation error:

  Line 33: val revision: String? = grgit.head()?.abbreviatedId
                                   ^ Unresolved reference: grgit

1 error

**Screenshots**

**EvergreenHUD Info (please complete the following information):**
- Mod Version: I don't know
- 1.18

**Additional context**
I run manjaro kde linux.

**Comment by isXander** [comment]
grgit died for some reason

**Comment by isXander** [comment]
why build? github actions exist https://github.com/isXander/EvergreenHUD/actions

**Comment by LuciusofLegend** [comment]
Oh, I didn't notice github actions XD  Lemme check that out.
