### ISSUE TITLE
Bug Report: Crash when trying to open the GUI [kotlin-rewrite/fabric1.17.1]

### ISSUE THREAD

**Issue by moehreag** [isXander/EvergreenHUD#28]
**Describe the bug**
By pressing the Hotkey assigned to open the GUI, the game crashes with an "Unexpected Error".

**To Reproduce**
0.5. Compile branch 'kotlin-rewrite' using "chmod +x gradlew" & "./gradlew build"
1. Try to open the GUI.
2. See error

**Expected behavior**
The GUI (as shown in the various screenshots) opens.

**Crash report**
First crash report (with other mods installed in my normal usecase):
[crash-2021-08-08_17.32.33-client.txt](https://github.com/isXander/EvergreenHUD/files/6951035/crash-2021-08-08_17.32.33-client.txt)
Second crash report (in a testing envroiment to ensure the crash is not caused by any other mod in conflict):
[crash-2021-08-08_17.38.14-client.txt](https://github.com/isXander/EvergreenHUD/files/6951044/crash-2021-08-08_17.38.14-client.txt)

**EvergreenHUD Info (please complete the following information):**
 - Mod Version: EvergreenHUD (fabric-1.17.1-2.0.0-pre.13) (self-compiled as stated above)
 - fabric-api version 0.35.1+1.17
 - Minecraft Version 1.17.1/fabric

**Additional context**
This may be caused by an error during compilation ([compilation_evergreenhud.txt](https://github.com/isXander/EvergreenHUD/files/6951055/compilation_evergreenhud.txt)), but I thought it only disrupted the forge version also packed in the gradle buildscript since the fabric version compiled first. Additionally, I would really like to help working on the multi-version part but since I'm really bad at java and/or kotlin I think I can't do much except finding bugs and reporting them. I also think that EvergreenHUD could be a good replacement for KronHUD (https://github.com/DarkKronicle/KronHUD) which is not currently being worked on by the author. On top, I encountered that only one of my friends still plays in 1.8.9 for pvping, all other (including me) already switched to 1.16+, so I think updating/porting the mod to newer versions is good work for the future.
If its easier for communicating, I joined the discord server already (the same pfp as in github or flip73#1552).

**Comment by moehreag** [comment]
After looking deeper into this mod, it seems like the rewrite for 1.17.1 is too WIP to report bugs about.

**Comment by isXander** [comment]
Very true, however bug reports are still very helpful. I will add a beta label to the issue.

On the note of the actual issue, it seems like Vigilance's fault. So I am kind of just waiting for them to fix it.
