### ISSUE TITLE
Suggestion: Change LICENSE from GPL-3.0 to LGPL-3.0

### ISSUE THREAD

**Issue by moehreag** [isXander/EvergreenHUD#31]
GPL can't be used since Minecraft itself is (sadly) proprietary. This would be solved with using the LGPL or MIT Licesnse.

**Comment by js6pak** [comment]
https://www.gnu.org/licenses/gpl-faq.en.html#GPLAndPlugins
> However, you can resolve that legal problem by adding an exception to your plug-in's license, giving permission to link it with the nonfree main program

Or just add an exception, but I don't think anyone cares anyway

**Comment by isXander** [comment]
LGPL is used in the [kotlin rewrite branch](/isXander/EvergreenHUD/tree/kotlin-rewrite). main branch is maintenance only

**Comment by moehreag** [comment]
Ok, good to know
