### ISSUE TITLE
Outdated Mod?

### ISSUE THREAD

**Issue by KualaBear** [isXander/EvergreenHUD#46]
Whenever I run mc it tells me the mod is outdated and told me to update it, but I don't know where to update it.

**Comment by Wyvest** [comment]
> 
> 
> Whenever I run mc it tells me the mod is outdated and told me to update it, but I don't know where to update it.

Are you downloading EvergreenHUD from Modrinth? (If not, use https://modrinth.com/mod/evergreenhud/version/3jI76xvU)
