### ISSUE TITLE
Add-on system does not verify entrypoint existence

### ISSUE THREAD

**Issue by monkuous** [isXander/EvergreenHUD#64]
# Description
While loading add-ons, the loader does not verify the specified entry point exists. This causes any add-ons that specify a nonexistent entry point to stop all further add-on discovery and possibly break the entire mod. Relevant code snippet:
https://github.com/isXander/EvergreenHUD/blob/5461c993380ccb30a84c9b16d67e821a7713e4a7/core/src/main/kotlin/dev/isxander/evergreenhud/addons/AddonLoader.kt#L44-L45
# Reproduction
Create an add-on that specifies an entry point that does not exist, either by specifying a nonexistent class or nonexistent method. Observe that, while loading, it will cause any add-ons that haven't been discovered yet to not be registered and possibly halt mod initialization or crash the game.
# Proposed Solution
This issue could be fixed by wrapping the for loop body in a try-catch that catches at least ClassNotFoundException and NoSuchMethodException:
```kotlin
            for (entrypoint in entrypoints) {
                try {
                    val split = entrypoint.split("::")
                    val className = split[0]
                    val methodName = split[1].substringBefore('(')


                    val method = Class.forName(className)
                        .getDeclaredMethod(methodName)

                    this.entrypoints.add { method.invoke(null) }
                } catch (e: Exception) {
                    // Log the exception and continue discovering add-ons
                }
            }
```

**Comment by isXander** [comment]
Fixed in 27b1cf92d90aec26fab16efc929d8a49dd390935
