### ISSUE TITLE
CPS Display does not go above 7-8

### ISSUE THREAD

**Issue by NightMasterX** [isXander/EvergreenHUD#65]
The CPS Display in Evergreen HUD does not go above 7-8 while in Sk1er's Keystrokes mod it registers all of the clicks. I have tested it on https://cpstest.org and I get 12-13 CPS there too.

**Comment by Wyvest** [comment]
try setting the CPS type to RAW instead of Controls

**Comment by NightMasterX** [comment]
That seem to fixed it :)
