### ISSUE TITLE
Hide gui while in replay viewer

### ISSUE THREAD

**Issue by leafable** [isXander/EvergreenHUD#66]
Please make it so that it automatically hides the evergreen hud while in the replay viewer. The hud overlaps with the replay GUI and it gets pretty annoying at times. Thank you!
![annoying](https://user-images.githubusercontent.com/90823678/133920837-b315b8ac-cae9-48c6-9c2a-48beeb86215a.png)

**Comment by RaderRMT** [comment]
no?
