### ISSUE TITLE
LunarSpoof (link)

### ISSUE THREAD

**Issue by bolinhosafado** [isXander/EvergreenHUD#87]
Direct link of the mod there in the hub git without having to use the gradle

**Comment by Wyvest** [comment]
Please elaborate. What does LunarSpoof have to do with EvergreenHUD, and why do you need to use gradle in the first place?

**Comment by Wyvest** [comment]
If you're actually talking about LunarSpoof, it's still in a very early beta from what I know, and EvergreenHUD's download is on Modrinth: https://modrinth.com/mod/evergreenhud/
